from .models import Opportunity

OPPORTUNITIES = [
    Opportunity(
        id="op-usdc-hsk-usdt",
        title="USDC → HSK → USDT route edge",
        kind="stablecoin_route",
        route=("USDC", "HSK", "USDT"),
        protocol="HashKey DEX mock",
        capital_required_usd=8,
        gross_edge_bps=42,
        estimated_gas_usd=0.015,
        estimated_slippage_bps=9,
        liquidity_usd=72_000,
        risk_score=21,
        confidence=76,
        description="A small route improvement appears after an HSK pool imbalance.",
        green_flags=("Blue-chip route", "Good liquidity", "No approval anomaly"),
    ),
    Opportunity(
        id="op-hsk-pool-imbalance",
        title="HSK pool imbalance rebalance",
        kind="pool_imbalance",
        route=("USDT", "HSK"),
        protocol="HorizonSwap mock",
        capital_required_usd=14,
        gross_edge_bps=68,
        estimated_gas_usd=0.022,
        estimated_slippage_bps=46,
        liquidity_usd=11_200,
        risk_score=44,
        confidence=61,
        description="Temporary imbalance between USDT/HSK pools creates a possible tiny edge.",
        red_flags=("Edge sensitive to slippage",),
        green_flags=("Token allowlist passed",),
    ),
    Opportunity(
        id="op-safe-claim",
        title="Verified ecosystem claim",
        kind="safe_claim",
        route=("CLAIM", "HSK"),
        protocol="HashFans campaign mock",
        capital_required_usd=0,
        gross_edge_bps=120,
        estimated_gas_usd=0.011,
        estimated_slippage_bps=0,
        liquidity_usd=100_000,
        risk_score=18,
        confidence=70,
        description="A verified claim with no approval request and a fixed reward.",
        green_flags=("No approval", "Verified contract", "Known campaign"),
    ),
    Opportunity(
        id="op-fake-airdrop",
        title="Free HSK MegaDrop claim",
        kind="suspicious_claim",
        route=("CLAIM", "UNKNOWN"),
        protocol="Unknown claim site",
        capital_required_usd=0,
        gross_edge_bps=900,
        estimated_gas_usd=0.016,
        estimated_slippage_bps=0,
        liquidity_usd=0,
        risk_score=96,
        confidence=93,
        description="Looks like a free airdrop, but asks for unlimited approval to an unknown operator.",
        red_flags=("Unlimited approval", "Unknown operator", "Fresh contract", "Method mismatch"),
        approval_request="unlimited_approval",
        verified_contract=False,
    ),
    Opportunity(
        id="op-high-apy-trap",
        title="800% APY tiny farm",
        kind="high_apy_trap",
        route=("USDC", "NEWCOIN"),
        protocol="YieldGoblin mock",
        capital_required_usd=20,
        gross_edge_bps=220,
        estimated_gas_usd=0.032,
        estimated_slippage_bps=155,
        liquidity_usd=1_900,
        risk_score=88,
        confidence=54,
        description="High APY farm with thin liquidity and unverified reward token.",
        red_flags=("Liquidity too thin", "Unverified contract", "High slippage", "Unknown token"),
        verified_contract=False,
    ),
    Opportunity(
        id="op-usdc-usdt-direct",
        title="USDC → USDT direct route improvement",
        kind="dex_route",
        route=("USDC", "USDT"),
        protocol="HashKey DEX mock",
        capital_required_usd=10,
        gross_edge_bps=19,
        estimated_gas_usd=0.012,
        estimated_slippage_bps=5,
        liquidity_usd=140_000,
        risk_score=12,
        confidence=82,
        description="Tiny stablecoin route improvement; boring but survivable.",
        green_flags=("Stablecoin-only", "Deep liquidity", "Low slippage"),
    ),
]
